package com.mashuktamim.inhale

object Quotes {

    val GENERAL = listOf(
        "You are the sky. Everything else is just the weather." to "Pema Chödrön",
        "The present moment is the only moment available to us." to "Thích Nhất Hạnh",
        "Wherever you are, be all there." to "Jim Elliot",
        "Nothing is worth more than this day." to "Goethe",
        "Simplicity is the ultimate sophistication." to "Leonardo da Vinci",
        "Almost everything will work again if you unplug it for a few minutes — including you." to "Anne Lamott",
        "Nature does not hurry, yet everything is accomplished." to "Lao Tzu",
        "Breathe. You are exactly where you need to be." to "Unknown",
        "Attention is the rarest and purest form of generosity." to "Simone Weil",
        "The best way to capture moments is to pay attention." to "Jon Kabat-Zinn",

        "The ability to simplify means to eliminate the unnecessary so that the necessary may speak." to "Hans Hofmann",
        "Live in the sunshine, swim the sea, drink the wild air." to "Ralph Waldo Emerson",
        "Be where your feet are." to "Unknown",
        "Slow down and enjoy life." to "Unknown",
        "Almost everything will work again if you unplug it for a few minutes." to "Anne Lamott",
        "The quieter you become, the more you can hear." to "Ram Dass",
        "To be everywhere is to be nowhere." to "Seneca",
        "It is not enough to be busy. So are the ants. The question is: What are we busy about?" to "Henry David Thoreau",
        "Life is really simple, but we insist on making it complicated." to "Confucius",
        "The greatest wealth is to live content with little." to "Plato",

        "We need the quiet hour, or simply the quiet." to "Unknown",
        "Disconnect to reconnect." to "Unknown",
        "Sometimes you need to disconnect and enjoy your own company." to "Unknown",
        "Your attention is your life." to "Unknown",
        "What you pay attention to grows." to "Unknown",
        "Where attention goes, energy flows." to "James Redfield",
        "The ability to be in the present moment is a major component of mental wellness." to "Abraham Maslow",
        "Be present in all things and thankful for all things." to "Maya Angelou",
        "The here and now is all we have, and if we play it right it's all we'll need." to "Ann Richards",
        "The present changes the past." to "Unknown",

        "Life is available only in the present moment." to "Thích Nhất Hạnh",
        "The real meditation practice is how we live our lives from moment to moment to moment." to "Jon Kabat-Zinn",
        "Mindfulness isn't difficult, we just need to remember to do it." to "Sharon Salzberg",
        "If you want to conquer the anxiety of life, live in the moment, live in the breath." to "Amit Ray",
        "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor." to "Thích Nhất Hạnh",
        "Smile, breathe, and go slowly." to "Thích Nhất Hạnh",
        "Walk as if you are kissing the Earth with your feet." to "Thích Nhất Hạnh",
        "The mind is everything. What you think you become." to "Buddha",
        "Peace comes from within. Do not seek it without." to "Buddha",
        "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path." to "Buddha",

        "The greatest step towards a life of simplicity is to learn to let go." to "Steve Maraboli",
        "Have nothing in your house that you do not know to be useful, or believe to be beautiful." to "William Morris",
        "Simplicity is the keynote of all true elegance." to "Coco Chanel",
        "Simplicity is the glory of expression." to "Walt Whitman",
        "The simplest things are often the truest." to "Richard Bach",
        "Less is more." to "Ludwig Mies van der Rohe",
        "Live simply so that others may simply live." to "Mahatma Gandhi",
        "Simplicity is making the journey of this life with just baggage enough." to "Charles Dudley Warner",
        "Our life is frittered away by detail. Simplify, simplify." to "Henry David Thoreau",
        "A simple life is not seeing how little we can get by with — that's poverty — but how efficiently we can put first things first." to "Victoria Moran",

        "The world is full of magic things, patiently waiting for our senses to grow sharper." to "W. B. Yeats",
        "In every walk with nature one receives far more than he seeks." to "John Muir",
        "And into the forest I go, to lose my mind and find my soul." to "John Muir",
        "The clearest way into the Universe is through a forest wilderness." to "John Muir",
        "Look deep into nature, and then you will understand everything better." to "Albert Einstein",
        "Adopt the pace of nature: her secret is patience." to "Ralph Waldo Emerson",
        "The earth has music for those who listen." to "William Shakespeare",
        "I took a walk in the woods and came out taller than the trees." to "Henry David Thoreau",
        "Heaven is under our feet as well as over our heads." to "Henry David Thoreau",
        "All good things are wild and free." to "Henry David Thoreau",

        "In wildness is the preservation of the world." to "Henry David Thoreau",
        "The mountains are calling and I must go." to "John Muir",
        "The poetry of the earth is never dead." to "John Keats",
        "Nature always wears the colors of the spirit." to "Ralph Waldo Emerson",
        "The goal of life is to make your heartbeat match the beat of the universe." to "Joseph Campbell",
        "Going to the mountains is going home." to "John Muir",
        "A walk in nature walks the soul back home." to "Mary Davis",
        "Nature is not a place to visit. It is home." to "Gary Snyder",
        "The forest is not merely an expression or representation of sacredness, nor a place to find it; the forest is sacred." to "Mary Austin",
        "Those who contemplate the beauty of the earth find reserves of strength that will endure as long as life lasts." to "Rachel Carson",

        "Almost everything important will happen if you stop scrolling." to "Unknown",
        "You don't have to respond to everything." to "Unknown",
        "Not every notification deserves your attention." to "Unknown",
        "Your phone is a tool, not a place to live." to "Unknown",
        "You were not born to check notifications." to "Unknown",
        "The internet is infinite. Your attention is not." to "Unknown",
        "Don't let a device become the place where your life happens." to "Unknown",
        "Look up. The world is still here." to "Unknown",
        "Put the phone down and pick your life up." to "Unknown",
        "The world outside your screen is waiting for you." to "Unknown",

        "You cannot find peace by avoiding life." to "Virginia Woolf",
        "Almost everything you want is on the other side of fear." to "Jack Canfield",
        "The privilege of a lifetime is to become who you truly are." to "Carl Jung",
        "Knowing yourself is the beginning of all wisdom." to "Aristotle",
        "Be yourself; everyone else is already taken." to "Oscar Wilde",
        "The only journey is the one within." to "Rainer Maria Rilke",
        "Knowing others is intelligence; knowing yourself is true wisdom." to "Lao Tzu",
        "The soul always knows what to do to heal itself. The challenge is to silence the mind." to "Caroline Myss",
        "Your life is the sum of your choices." to "Albert Camus",
        "You have power over your mind — not outside events. Realize this, and you will find strength." to "Marcus Aurelius",

        "We are what we repeatedly do." to "Aristotle",
        "The chains of habit are too weak to be felt until they are too strong to be broken." to "Samuel Johnson",
        "First we make our habits, then our habits make us." to "John Dryden",
        "Small disciplines repeated with consistency every day lead to great achievements." to "John C. Maxwell",
        "Motivation is what gets you started. Habit is what keeps you going." to "Jim Ryun",
        "The secret of getting ahead is getting started." to "Mark Twain",
        "Do something today that your future self will thank you for." to "Unknown",
        "A year from now you may wish you had started today." to "Karen Lamb",
        "Success is the sum of small efforts, repeated day in and day out." to "Robert Collier",
        "Great things are done by a series of small things brought together." to "Vincent van Gogh",

        "Almost everything is noise. Find what matters." to "Unknown",
        "Silence is a source of great strength." to "Lao Tzu",
        "Silence is beautiful, not awkward." to "Unknown",
        "Sometimes the most productive thing you can do is relax." to "Mark Black",
        "Rest is not idleness." to "John Lubbock",
        "There is more to life than increasing its speed." to "Mahatma Gandhi",
        "Slow living is not about doing less. It is about doing what matters." to "Unknown",
        "The time you enjoy wasting is not wasted time." to "Marthe Troly-Curtin",
        "Almost all of the things you worry about are not worth worrying about." to "Unknown",
        "Do less, with more intention." to "Unknown",

        "Be still and know." to "Psalm 46:10",
        "Solitude is where I place my chaos to rest and awaken my inner peace." to "Nikki Rowe",
        "Loneliness is the poverty of self; solitude is richness of self." to "May Sarton",
        "The best thinking has been done in solitude." to "Thomas Edison",
        "Solitude matters, and for some people, it's the air they breathe." to "Susan Cain",
        "All of humanity's problems stem from man's inability to sit quietly in a room alone." to "Blaise Pascal",
        "In solitude the mind gains strength and learns to lean upon itself." to "Laurence Sterne",
        "The more powerful and original a mind, the more it will incline towards the religion of solitude." to "Aldous Huxley",
        "Sometimes you need to sit alone, on the floor, in a quiet room, in order to hear yourself." to "Unknown",
        "Solitude is fine but you need someone to tell that solitude is fine." to "Honoré de Balzac",

        "Happiness depends upon ourselves." to "Aristotle",
        "Very little is needed to make a happy life; it is all within yourself." to "Marcus Aurelius",
        "The happiness of your life depends upon the quality of your thoughts." to "Marcus Aurelius",
        "If you want to be happy, be." to "Leo Tolstoy",
        "Happiness is not something ready made. It comes from your own actions." to "Dalai Lama",
        "The best way to pay for a lovely moment is to enjoy it." to "Richard Bach",
        "Joy is not in things; it is in us." to "Benjamin Franklin",
        "Be grateful for what you have; you will end up having more." to "Oprah Winfrey",
        "Enjoy the little things, for one day you may look back and realize they were the big things." to "Robert Brault",
        "The present moment is filled with joy and happiness. If you are attentive, you will see it." to "Thích Nhất Hạnh",

        "What we choose to focus on and what we choose to ignore plays in defining the quality of our life." to "Cal Newport",
        "Clarity about what matters provides clarity about what does not." to "Cal Newport",
        "A deep life is a good life." to "Cal Newport",
        "Digital minimalism is a philosophy that helps you question what digital communication tools add the most value to your life." to "Cal Newport",
        "Spend enough time in solitude to hear your own voice." to "Cal Newport",
        "Your ability to concentrate is your most valuable asset." to "Cal Newport",
        "The ability to concentrate without distraction is becoming increasingly valuable." to "Cal Newport",
        "If you don't control your attention, someone else will." to "Unknown",
        "Attention is the beginning of devotion." to "Mary Oliver",
        "Pay attention. Be astonished. Tell about it." to "Mary Oliver",

        "Tell me, what is it you plan to do with your one wild and precious life?" to "Mary Oliver",
        "Instructions for living a life: Pay attention. Be astonished. Tell about it." to "Mary Oliver",
        "I don't want to end up simply having visited this world." to "Mary Oliver",
        "Keep some room in your heart for the unimaginable." to "Mary Oliver",
        "You do not have to be good. You do not have to walk on your knees for a hundred miles through the desert." to "Mary Oliver",
        "Let yourself be silently drawn by the strange pull of what you really love." to "Rumi",
        "What you seek is seeking you." to "Rumi",
        "The quieter you become, the more you are able to hear." to "Rumi",
        "Don't be satisfied with stories, how things have gone with others. Unfold your own myth." to "Rumi",
        "Stop acting so small. You are the universe in ecstatic motion." to "Rumi",

        "The mind, once stretched by a new idea, never returns to its original dimensions." to "Ralph Waldo Emerson",
        "The only way out is through." to "Robert Frost",
        "Nothing can bring you peace but yourself." to "Ralph Waldo Emerson",
        "For every minute you are angry you lose sixty seconds of happiness." to "Ralph Waldo Emerson",
        "Write it on your heart that every day is the best day in the year." to "Ralph Waldo Emerson",
        "Live your life and forget your age." to "Norman Vincent Peale",
        "The future depends on what you do today." to "Mahatma Gandhi",
        "An ounce of action can crush a ton of fear." to "Tim Fargo",
        "The best time to plant a tree was 20 years ago. The second best time is now." to "Proverb",
        "Yesterday is history, tomorrow is a mystery, today is God's gift, that's why we call it the present." to "Unknown"
    )

    val ISLAMIC = listOf(
        // Qur'an — Time, Presence & Reflection
        "By time, surely humanity is in loss." to "Qur'an 103:1–2",
        "Except those who have faith, do good, and urge each other to the truth and patience." to "Qur'an 103:3",
        "Let every soul look to what it has sent forth for tomorrow." to "Qur'an 59:18",
        "And do not be like those who forgot Allah, so He made them forget themselves." to "Qur'an 59:19",
        "And remember your Lord when you forget." to "Qur'an 18:24",
        "Remember Me; I will remember you." to "Qur'an 2:152",
        "Remember your Lord within yourself, humbly and with awe." to "Qur'an 7:205",
        "Remember Allah with frequent remembrance." to "Qur'an 33:41",
        "Those who believe and whose hearts find rest in the remembrance of Allah." to "Qur'an 13:28",
        "Surely, in the remembrance of Allah do hearts find rest." to "Qur'an 13:28",

        // Qur'an — Worldly Distraction
        "The life of this world is only play and amusement." to "Qur'an 6:32",
        "The life of this world is nothing but play and amusement." to "Qur'an 29:64",
        "Know that the life of this world is only play, amusement, luxury, and boasting." to "Qur'an 57:20",
        "The Hereafter is better and more lasting." to "Qur'an 87:17",
        "The Hereafter is better for those who are mindful of Allah." to "Qur'an 6:32",
        "Do not let your wealth and children distract you from the remembrance of Allah." to "Qur'an 63:9",
        "And whoever turns away from My remembrance will certainly have a miserable life." to "Qur'an 20:124",
        "Wealth and children are only an adornment of this worldly life." to "Qur'an 18:46",
        "Whatever you have will end, but what Allah has is everlasting." to "Qur'an 16:96",
        "What is with Allah is better and more lasting." to "Qur'an 28:60",

        // Qur'an — Patience & Peace
        "Seek help through patience and prayer." to "Qur'an 2:45",
        "Indeed, Allah is with those who are patient." to "Qur'an 2:153",
        "Surely, with hardship comes ease." to "Qur'an 94:5",
        "Indeed, with hardship comes ease." to "Qur'an 94:6",
        "Allah does not burden a soul beyond what it can bear." to "Qur'an 2:286",
        "Allah intends ease for you and does not intend hardship for you." to "Qur'an 2:185",
        "And whoever is mindful of Allah, He will make a way out for them." to "Qur'an 65:2",
        "And whoever puts their trust in Allah, He is sufficient for them." to "Qur'an 65:3",
        "Indeed, Allah loves those who rely upon Him." to "Qur'an 3:159",
        "And be patient, for indeed Allah does not allow the reward of the good to be lost." to "Qur'an 11:115",

        // Qur'an — Gratitude
        "If you are grateful, I will certainly give you more." to "Qur'an 14:7",
        "And whatever blessing you have is from Allah." to "Qur'an 16:53",
        "Remember the favors of Allah upon you." to "Qur'an 5:7",
        "So remember Me; I will remember you. And be grateful to Me." to "Qur'an 2:152",
        "Whoever is grateful, it is only for their own good." to "Qur'an 31:12",
        "And few of My servants are truly grateful." to "Qur'an 34:13",
        "Eat from the good things We have provided for you and be grateful." to "Qur'an 2:172",
        "And We will surely reward those who are grateful." to "Qur'an 3:145",
        "Allah is Most Appreciative, All-Knowing." to "Qur'an 2:158",
        "If you are grateful, I will surely increase you." to "Qur'an 14:7",

        // Qur'an — Moderation & Simplicity
        "Eat and drink, but do not be excessive." to "Qur'an 7:31",
        "Do not be excessive. Surely, He does not like the excessive." to "Qur'an 7:31",
        "Those who spend are neither extravagant nor stingy, but follow a middle way." to "Qur'an 25:67",
        "Do not forget your share of the world." to "Qur'an 28:77",
        "Seek, through what Allah has given you, the home of the Hereafter." to "Qur'an 28:77",
        "And do good as Allah has been good to you." to "Qur'an 28:77",
        "Walk upon the earth humbly." to "Qur'an 25:63",
        "Do not walk on the earth arrogantly." to "Qur'an 17:37",
        "And do not waste, for Allah does not love the wasteful." to "Qur'an 6:141",
        "And the servants of the Most Merciful walk upon the earth humbly." to "Qur'an 25:63",

        // Qur'an — Speech & Attention
        "Speak to people good words." to "Qur'an 2:83",
        "And say that which is best." to "Qur'an 17:53",
        "Do not follow that of which you have no knowledge." to "Qur'an 17:36",
        "Indeed, the hearing, the sight, and the heart — all of those will be questioned." to "Qur'an 17:36",
        "O believers, avoid much suspicion." to "Qur'an 49:12",
        "And do not spy on one another." to "Qur'an 49:12",
        "Lower your gaze and guard your modesty." to "Qur'an 24:30",
        "And be moderate in your pace." to "Qur'an 31:19",
        "And lower your voice." to "Qur'an 31:19",
        "Good words and forgiveness are better than charity followed by injury." to "Qur'an 2:263",

        // Qur'an — Self & Inner Life
        "He has succeeded who purifies the soul." to "Qur'an 91:9",
        "And whoever purifies it has succeeded." to "Qur'an 91:9",
        "Successful indeed are the believers who are humble in their prayer." to "Qur'an 23:1–2",
        "Indeed, Allah does not change the condition of a people until they change what is within themselves." to "Qur'an 13:11",
        "And whoever fears Allah and is mindful of Him, He will make their matters easy." to "Qur'an 65:4",
        "Allah knows what is within the hearts." to "Qur'an 67:13",
        "We know what his soul whispers to him." to "Qur'an 50:16",
        "Do not despair of the mercy of Allah." to "Qur'an 39:53",
        "Indeed, Allah loves those who constantly repent." to "Qur'an 2:222",
        "Allah loves those who purify themselves." to "Qur'an 2:222",

        // Qur'an — Nature & Creation
        "Indeed, in the creation of the heavens and the earth are signs for people of understanding." to "Qur'an 3:190",
        "Those who remember Allah standing, sitting, and lying on their sides." to "Qur'an 3:191",
        "And they reflect on the creation of the heavens and the earth." to "Qur'an 3:191",
        "Our Lord, You did not create this without purpose." to "Qur'an 3:191",
        "So observe the effects of the mercy of Allah." to "Qur'an 30:50",
        "And in the earth are signs for those with certainty." to "Qur'an 51:20",
        "And in yourselves. Will you not then see?" to "Qur'an 51:21",
        "Do they not look at the sky above them, how We built it and adorned it?" to "Qur'an 50:6",
        "And the earth We have spread out and placed in it firm mountains." to "Qur'an 50:7",
        "And We made from water every living thing." to "Qur'an 21:30",

        // Hadith — Time
        "There are two blessings which many people do not appreciate: health and free time." to "Sahih al-Bukhari 6412",
        "Take advantage of five before five: your youth before your old age." to "Musnad Ahmad",
        "Your life before your death." to "Musnad Ahmad",
        "Your health before your illness." to "Musnad Ahmad",
        "Your free time before your busyness." to "Musnad Ahmad",
        "Your wealth before your poverty." to "Musnad Ahmad",
        "Be in this world as though you were a stranger or a traveler." to "Sahih al-Bukhari 6416",
        "When evening comes, do not expect to live until morning." to "Sahih al-Bukhari 6416",
        "When morning comes, do not expect to live until evening." to "Sahih al-Bukhari 6416",
        "Take from your health for your illness." to "Sahih al-Bukhari 6416",

        // Hadith — Speech & Silence
        "Whoever believes in Allah and the Last Day, let him speak good or remain silent." to "Sahih al-Bukhari 6018",
        "Part of the perfection of one's Islam is leaving what does not concern him." to "Jami' at-Tirmidhi 2317",
        "A Muslim is one from whose tongue and hand other Muslims are safe." to "Sahih al-Bukhari 10",
        "Whoever can guarantee what is between his jaws and legs, I guarantee him Paradise." to "Sahih al-Bukhari 6474",
        "Whoever believes in Allah and the Last Day, let him honor his neighbor." to "Sahih al-Bukhari 6018",
        "Whoever believes in Allah and the Last Day, let him honor his guest." to "Sahih al-Bukhari 6018",
        "Whoever believes in Allah and the Last Day, let him not harm his neighbor." to "Sahih al-Bukhari 6018",
        "A good word is charity." to "Sahih al-Bukhari 2989",
        "Every good deed is charity." to "Sahih al-Bukhari 6021",
        "Do not say anything which you will later regret." to "Jami' at-Tirmidhi",

        // Hadith — Balance & Self-Care
        "Your body has a right over you." to "Sahih al-Bukhari 5199",
        "Your eyes have a right over you." to "Sahih al-Bukhari 5199",
        "Your Lord has a right over you, your soul has a right over you, and your family has a right over you." to "Sahih al-Bukhari 1968",
        "The most beloved deeds to Allah are those that are consistent, even if they are few." to "Sahih al-Bukhari 6464",
        "The strong believer is better and more beloved to Allah than the weak believer." to "Sahih Muslim 2664",
        "Seek help from Allah and do not give up." to "Sahih Muslim 2664",
        "Be keen on what benefits you." to "Sahih Muslim 2664",
        "Seek help from Allah and do not be helpless." to "Sahih Muslim 2664",
        "Do not harm yourself or others." to "Sunan Ibn Majah 2341",
        "The best of you are those who are best to their families." to "Jami' at-Tirmidhi 3895",

        // Hadith — Contentment & Simplicity
        "Richness is not having many possessions. Rather, true richness is the richness of the soul." to "Sahih al-Bukhari 6446",
        "Look at those who are below you and do not look at those above you." to "Sahih al-Bukhari 6490",
        "Contentment is a treasure that never diminishes." to "Sunan Ibn Majah",
        "Successful is the one who embraces Islam, is granted sufficient provision, and Allah makes him content with what He has given him." to "Sahih Muslim 1054",
        "The world is a prison for the believer and a paradise for the disbeliever." to "Sahih Muslim 2956",
        "Be moderate and follow a middle course." to "Sahih al-Bukhari",
        "The most beloved places to Allah are the mosques." to "Sahih Muslim 671",
        "The world is sweet and green, and Allah has appointed you as successors in it." to "Sahih Muslim 2742",
        "Do not envy one another." to "Sahih al-Bukhari 6065",
        "Do not hate one another." to "Sahih al-Bukhari 6065",

        // Hadith — Mindfulness, Intention & Character
        "Actions are judged by intentions." to "Sahih al-Bukhari 1",
        "Every person will have only what they intended." to "Sahih al-Bukhari 1",
        "Allah does not look at your bodies or your appearance, but He looks at your hearts and deeds." to "Sahih Muslim 2564",
        "The most beloved people to Allah are those who are most beneficial to people." to "Al-Mu'jam al-Awsat",
        "None of you truly believes until he loves for his brother what he loves for himself." to "Sahih al-Bukhari 13",
        "The merciful are shown mercy by the Most Merciful." to "Jami' at-Tirmidhi 1924",
        "Do not belittle any good deed, even meeting your brother with a cheerful face." to "Sahih Muslim 2626",
        "A smile in the face of your brother is charity." to "Jami' at-Tirmidhi 1956",
        "Whoever does not show mercy will not be shown mercy." to "Sahih al-Bukhari 6013",
        "The best among you are those who have the best manners and character." to "Sahih al-Bukhari 3559"
    )

    fun getForType(type: Prefs.QuoteType): List<Pair<String, String>> = when (type) {
        Prefs.QuoteType.GENERAL -> GENERAL
        Prefs.QuoteType.ISLAMIC -> ISLAMIC
        Prefs.QuoteType.BOTH -> GENERAL + ISLAMIC
    }

    fun getRandom(type: Prefs.QuoteType): Pair<String, String> {
        val list = getForType(type)
        return if (list.isNotEmpty()) list.random() else GENERAL.random()
    }
}
